Extract data classes
a-sit-plus/vck pull request #115
Opened 2024-08-28 09:58 UTC by nodh

Move data classes for DIF and OpenID to separate modules, i.e. decoupling them from the vck logic.

2024-08-28 09:59 UTC, nodh commented
@JesusMcCloud  Please have a thorough look at the gradle files, because I'm sure there are some shorthand functions that I was not aware of for all those dependency declarations.

2024-08-28 10:31 UTC, n0900 requested changes

2024-08-28 10:31 UTC, n0900 commented on openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/Json.kt
Remove since it is replaced by `vckJsonSerializer`?

2024-08-28 12:49 UTC, nodh commented on openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/Json.kt
Can't remove, because that serializer here is used by the data classes

2024-08-28 13:00 UTC, n0900 approved these changes

2024-08-28 21:37 UTC, JesusMcCloud commented
I need to double-check, but I'm pretty sure most of the dependencies can go away, as they are transitive dependencies of signum. Tomorrow afternoon is a good time for this

2024-08-29 18:13 UTC, JesusMcCloud commented
let's keep it that way. I just created #117 to remind me of this, once everything is merged.

2024-08-30 10:14 UTC, merged