Fix serialization of byte arrays in SD-JWT
a-sit-plus/vck pull request #132
Opened 2024-09-19 13:17 UTC by nodh

This obviously doesn't work that well ...

2024-09-19 14:11 UTC, JesusMcCloud commented
context, please! what is going on any why?

2024-09-26 13:11 UTC, JesusMcCloud requested changes

2024-09-27 07:39 UTC, nodh commented on vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/SelectiveDisclosureItem.kt
> +    else -> JsonPrimitive(toString())
With this code, `this` is cast to `Nothing`, so it won't work:

```kotlin
when (this) {
    is Boolean,
    is Number -> JsonPrimitive(this)
}
```

2024-09-27 07:46 UTC, JesusMcCloud approved these changes

2024-09-27 07:59 UTC, merged